#### Python
There are several different ways to generate random numbers using Python. For this example, you will use the random package, so import it:

import random
Generating Numbers Between 0 and 1
The function to generate a single value from a uniform random variable between 0 and 1 is random.random(). You can save the number to a variable if you like (this one is called value and then use the print() function on it:

value = random.random()
print(value)
Running the above in Python will result in a single number between 0 and 1, with about 15 digits past the decimal.

Generating User-Specified Values
In order to get a random value between two other points - say 30 to 50, for example - you need to change the code just a bit. Now, instead of using the random function within the random package, you will use the random.uniform() function, as follows:

value = random.uniform(30, 50)
print(value)
All you need to do is specify the starting point (30) and the ending point (50).

Note that for all 4 methods listed above, random numbers were generated that are always positive. The method for generating a random number that is negative, say -30 to -12, or generating a random number that could be either negative or positive, say -5 to 5 is the same.



In [1]:
import random

In [2]:
price = random.random()
print(price)

0.9412349069587085


#### defaults to value between zero and one.

#### for user specified value

In [5]:
myvalue = random.uniform(30, 50)
print(myvalue)

43.191106708702044


### generating random numbers with a normal distribution

#### Generating the Standard Normal Distribution
As shown here, you can generate 5 random numbers according to the standard normal distribution (mean of zero, standard deviation of 1) with the package numpy. So start by importing it:

import numpy as np
Then you can create a vector of random numbers using the function np.random.normal() with the argument size= to specify how many random numbers you'd like:

x = np.random.normal(size = 5)
and then print it:

print(x)
Your results should look something like this:

[ 2.22430932 -0.81752269 -1.96034014 -0.44019808  2.08944964]
Generating a Normal Distribution Centered Elsewhere
In order to have the normal distribution centered somewhere other than 0, with a standard deviation other than 1, you need to do a little manipulation. Suppose you wanted a normal distribution centered at 50, with a standard deviation of 10? You could simply multiply the function by the standard deviation (10), and then add the mean (50):

x = (np.random.normal(size=5))*10 + 50
print(x)

In [6]:
import numpy as np

In [7]:
x = np.random.normal(size=5)
print(x)

[ 0.28325581  1.94030666 -1.05209189  0.73665637  0.24737451]


In [8]:
y=(np.random.normal(size=5))*10+50
print(y)

[56.99011923 41.86825861 40.9387031  62.01563357 36.49185589]


In [9]:
nrv= (np.random.normal(size=20))*50+100

In [10]:
print(nrv)

[191.24641172 -17.27749735  86.63262988 -11.02831995 119.78922833
  66.61739747  84.92006301 155.49689837 183.3361265  103.76866979
 137.66207785 127.81601743  55.73394915 146.24726236  94.91621082
 146.38306334  64.17859005  42.44226044 161.41598865 133.04197442]
